### ISSUE TITLE
Maximum number of iteration

### ISSUE THREAD

**Issue by ofbodur** [rbeucher/UWGeodynamics#48]
Hello Romain,

I realized that when the convergence is not achieved after maximum number of iteration, the code does not stop, but tries again from 0. Why?

**Comment by rbeucher** [comment]
I does not "try again", it moves to the next step.. starting from non-linear iteration number 0...
The code is less stubborn than the user, thankfully...;-)

**Comment by ofbodur** [comment]
So what if it never converges?

**Comment by rbeucher** [comment]
Well, that's why we have the maximum number of iteration. At some point you just give up... and move on...
More seriously, if your pb does not converge it can mean many things, maybe you are just doing something silly and it can not find a solution, maybe the pb is too hard, maybe the solver options you are using are not appropriate for the pb you are trying to solve... There is a lot of reason this could happen and there is no easy answer to why it's not converging. Tolerance could be too high...
If your model run for a lot of iterations and do not converge, you can look at the convergence pattern, if it's going down in a kind of monotonic way that's good. if not...well you have to think a bit more, simplify your pb, look at your boundary conditions... etc...It takes a lot of experience...

Viscoplastic model do not converge very well sometimes, because of the shear zones. It is then really dependent on the mesh resolution and your plastic implementation.
We could discuss that for ages, in the end it comes with experience, after trying many things...

**Comment by arijitlaik** [comment]
there's a utils function for logging solver convergence data, viscoplastic models do not converge below 2-2.5e-4 as per my model setups, reducing the dt from the one that is fetched by advector max dt helps quite a lot. there has been some recent talk about adaptive time stepping for this.
